### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by per1234** [DgFutureLab/satoyama-libs#1]
I'd like to add direct support to some of the projects I'm involved in for your ATmega1284P based variants in satoyama-libs/mighty-1284p-freaklabs/variants but I would need to use your pins_arduino.h files to do this. Any chance you could add license information to those files or the repository in general so I could see if this is possible? Thanks, Per

**Comment by halfdanrump** [comment]
Hey Per!

Feel free to use it! It's the same as https://github.com/maniacbug/mighty-1284p :). 

Yours,
Halfdan
